theme: jekyll-theme-cayman

layout: post
favicon: /img/favicon.ico

title: "language"

subtitle: "编程语言学习总结"

description: "欢迎来此学习" # 随便说点，描述一下

header-img: "img/img.jpg"
catalog: true

author: i-curve

github_username: i-curve # 你的github账号
